'use strict';

export const NOTIFICATION_DURATION_SHORT_MS = 4000;
export const NOTIFICATION_DURATION_LONG_MS = 10000;
export const NOTIFICATION_DURATION_INDEFINITE = null;
export const NOTIFICATION_MIN_ALERT_VISIBLE_MS = 5000;
export const NOTIFICATION_SPAM_WINDOW_MS = 800;
