/**
 * Shared utility functions for CSS and XPath selector generators: text cleaning,
 * attribute stability checks, and ancestor traversal helpers.
 * Runs in the content-script context; no async I/O.
 * Invariant: stability predicates are pure — they never mutate the element.
 * Called by: css/generator.js, xpath/generator.js, and their strategy modules.
 */
import { get } from '../../config/defaults.js';
import logger from '../../infrastructure/logger.js';

// Lazily compiled from config strings — reset to null if config ever changes.
let _compiledIdPatterns = null;
let _compiledClassPatterns = null;

/** Lazily compiles and caches ID instability patterns from config. */
function getIdPatterns() {
  if (!_compiledIdPatterns) {
    _compiledIdPatterns = get('attributes.dynamicIdPatterns').map(p =>
      typeof p === 'string' ? new RegExp(p) : p
    );
  }
  return _compiledIdPatterns;
}

/** Lazily compiles and caches class instability patterns from config. */
function getClassPatterns() {
  if (!_compiledClassPatterns) {
    _compiledClassPatterns = get('attributes.dynamicClassPatterns').map(p =>
      typeof p === 'string' ? new RegExp(p) : p
    );
  }
  return _compiledClassPatterns;
}

const WHITESPACE_PATTERN = /\s+/g;
const LINE_BREAKS_PATTERN = /[\r\n\t]+/g;

/** Collapses all whitespace and line-break sequences in `text` to a single space. */
export function cleanText(text) {
  if (typeof text !== 'string') {return '';}
  return text.replace(LINE_BREAKS_PATTERN, ' ').replace(WHITESPACE_PATTERN, ' ').trim();
}

/**
 * Collects all `data-*` attributes from an element into a plain object.
 * Returns an empty object on error rather than throwing.
 *
 * @param {Element|null} element
 * @returns {Record<string, string>}
 */
export function getDataAttributes(element) {
  if (!element) {return {};}

  const dataAttrs = {};
  try {
    for (const attr of element.attributes) {
      if (attr.name.startsWith('data-')) {
        dataAttrs[attr.name] = attr.value;
      }
    }
  } catch (error) {
    logger.warn('Failed to get data attributes', {
      error: error.message,
      element: element.tagName
    });
  }

  return dataAttrs;
}

/**
 * Returns an XPath-compatible tag expression for SVG and MathML elements where
 * `tagName` is namespace-prefixed and cannot be used directly in an XPath predicate.
 *
 * @param {Element} element
 * @returns {string} Lowercase tag name or `*[local-name()='…']` for foreign-namespace elements.
 */
export function getUniversalTag(element) {
  const ns = element.namespaceURI;

  if (ns === 'http://www.w3.org/2000/svg' || ns === 'http://www.w3.org/1998/Math/MathML') {
    return `*[local-name()='${element.localName}']`;
  }

  return element.tagName.toLowerCase();
}

/**
 * Returns true when `id` is unlikely to be dynamically generated.
 * Length bounds (2–200) exclude single-char IDs and auto-generated GUIDs.
 *
 * @param {string} id
 * @returns {boolean}
 */
export function isStableId(id) {
  if (!id || id.length < 2 || id.length > 200) {return false;}
  return !getIdPatterns().some(pattern => pattern.test(id));
}

/**
 * Returns true when `value` does not match known patterns for generated or ephemeral values
 * (timestamps, UUIDs, Ember/React component IDs, etc.).
 *
 * @param {string|*} value - Attribute value to test.
 * @returns {boolean}
 */
export function isStableValue(value) {
  const UNSTABLE_VALUE_PATTERNS = [
    /^[0-9]{8,}$/, /^[a-f0-9]{8}-[a-f0-9]{4}/i, /data-aura-rendered/i,
    /^ember\d+$/i, /^react\d+$/i, /^\d{13}$/, /^tt-for-\d+$/i,
    /^[0-9]+:[0-9]+;[a-z]$/i, /-\d+-\d+$/
  ];

  if (!value || typeof value !== 'string') {return false;}
  if (value.length < 1 || value.length > 200) {return false;}
  return !UNSTABLE_VALUE_PATTERNS.some(pattern => pattern.test(value));
}

/**
 * Returns true when a CSS class name is not generated by a CSS-in-JS runtime or build tool.
 * Empty strings and whitespace-only values are always rejected.
 *
 * @param {string|*} className
 * @returns {boolean}
 */
export function isStableClass(className) {
  if (!className || typeof className !== 'string' || className.trim().length === 0) {
    return false;
  }

  const trimmed = className.trim();

  return !getClassPatterns().some(pattern => pattern.test(trimmed));
}

/**
 * Returns true when `text` looks like static human-readable content rather than
 * a generated value (counters, timestamps, prices, loading states).
 *
 * @param {string|*} text
 * @returns {boolean}
 */
export function isStaticText(text) {
  if (!text || typeof text !== 'string') {return false;}
  if (text.length < 2 || text.length > 200) {return false;}

  const dynamicPatterns = [
    /^\d+$/, /^[0-9]{8,}$/, /^[a-f0-9]{8}-[a-f0-9]{4}/i,
    /^\d{1,2}:\d{2}/, /^\d{1,2}\/\d{1,2}\/\d{2,4}$/,
    /^loading/i, /^processing/i, /^\$\d+\.\d{2}$/
  ];

  return !dynamicPatterns.some(pattern => pattern.test(text));
}

/**
 * Returns all stable attributes on `element` ordered by priority (test attrs first,
 * then supplementary, then data-*). Excludes unstable or missing values.
 *
 * @param {Element} element
 * @returns {Array<{name: string, value: string}>}
 */
export function collectStableAttributes(element) {
  const attrs = [];

  try {
    const testAttrs = get('attributes.priority');
    for (const attr of testAttrs) {
      const value = element.getAttribute(attr);
      if (value && isStableValue(value)) {
        attrs.push({ name: attr, value });
      }
    }

    const supplementary = [...get('attributes.supplementary'), 'class'];
    for (const attr of supplementary) {
      const value = element.getAttribute(attr);
      if (value && isStableValue(value) && !attrs.find(a => a.name === attr)) {
        attrs.push({ name: attr, value });
      }
    }

    const dataAttrs = getDataAttributes(element);
    for (const [name, value] of Object.entries(dataAttrs)) {
      if (isStableValue(value) && !attrs.find(a => a.name === name)) {
        attrs.push({ name, value });
      }
    }
  } catch (error) {
    logger.warn('Failed to collect stable attributes', {
      error: error.message,
      element: element.tagName
    });
  }

  return attrs;
}

/**
 * Returns the highest-priority stable attribute on `element`, or null if none exist.
 * Convenience wrapper over `collectStableAttributes`.
 *
 * @param {Element} element
 * @returns {{name: string, value: string}|null}
 */
export function getBestAttribute(element) {
  const attrs = collectStableAttributes(element);
  return attrs.length > 0 ? attrs[0] : null;
}

/**
 * Walks up the ancestor chain collecting elements that have at least one stable attribute.
 * Stops at `maxDepth` ancestors or the document root, whichever comes first.
 *
 * @param {Element} element
 * @param {number} maxDepth
 * @returns {Array<{element: Element, attr: {name: string, value: string}, depth: number}>}
 */
export function getStableAncestorChain(element, maxDepth) {
  const ancestors = [];
  let current = element.parentElement;
  let depth = 0;

  while (current && depth < maxDepth) {
    const attr = getBestAttribute(current);
    if (attr) {
      ancestors.push({ element: current, attr, depth });
    }
    current = current.parentElement;
    depth++;
  }

  return ancestors;
}

/**
 * Walks up the ancestor chain looking for a semantic landmark element that also
 * has a stable attribute — a reliable anchor for relative selectors.
 * Caps the search at 8 levels to avoid O(n) walks on deeply nested DOMs.
 *
 * @param {Element} element
 * @returns {Element|null} The first qualifying ancestor, or null.
 */
export function findBestSemanticAncestor(element) {
  const SEMANTIC_TAGS = [
    'form', 'nav', 'header', 'footer', 'main', 'section', 'article',
    'aside', 'dialog', 'table', 'fieldset', 'figure'
  ];

  let current = element.parentElement;
  let depth = 0;

  while (current && depth < 8) {
    const tag = current.tagName.toLowerCase();

    if (SEMANTIC_TAGS.includes(tag)) {
      const attr = getBestAttribute(current);
      if (attr) {return current;}
    }

    current = current.parentElement;
    depth++;
  }

  return null;
}